-- Execute uma única vez no SQL Editor do Supabase.
create table if not exists public.sync_events (
    id bigint generated by default as identity primary key,
    topic text not null,
    payload jsonb not null,
    created_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint)
);

create table if not exists public.sync_state (
    scope text primary key,
    payload jsonb not null,
    updated_at bigint not null default ((extract(epoch from clock_timestamp()) * 1000)::bigint)
);

create index if not exists sync_events_created_at_idx on public.sync_events (created_at);

alter table public.sync_events enable row level security;
alter table public.sync_state enable row level security;

drop policy if exists "canela_read_events" on public.sync_events;
drop policy if exists "canela_insert_events" on public.sync_events;
drop policy if exists "canela_read_state" on public.sync_state;
drop policy if exists "canela_insert_state" on public.sync_state;
drop policy if exists "canela_update_state" on public.sync_state;

create policy "canela_read_events" on public.sync_events for select to anon using (true);
create policy "canela_insert_events" on public.sync_events for insert to anon with check (true);
create policy "canela_read_state" on public.sync_state for select to anon using (true);
create policy "canela_insert_state" on public.sync_state for insert to anon with check (true);
create policy "canela_update_state" on public.sync_state for update to anon using (true) with check (true);

-- Mantém apenas sete dias de eventos transitórios; o estado consolidado fica em sync_state.
create or replace function public.canela_cleanup_sync_events()
returns void
language sql
security definer
set search_path = public
as $$
    delete from public.sync_events
    where created_at < ((extract(epoch from clock_timestamp()) * 1000)::bigint - 604800000);
$$;
